### ISSUE TITLE
Use to populate outgoing links.

### ISSUE THREAD

**Issue by krsmrs** [bilbof/purser#6]
Script is great!
I guess it would be easy to use this to populate outgoing links with the utm parameters?
Could you document?

**Comment by bilbof** [comment]
Hey @krsmrs, I'm glad that this is useful for you!

Could you provide more details on what you are after?

If you have a link like `<a href="google.com?utm_source=my-website">Link</a>`, and you'd like to track when a user clicks on this, you would probably need to write some custom code.

For example:

```
<a class>Link</a>

<script>
// Set up link using jQuery
var link = $('.link')
link.data("url", "https://google.co.uk?utm_source=my-website");
link.data("website", "google");

// Create event handler
link.on('click', function(event) {
    // Update purser
    purser.update({
       'website_clicked': this.data('website')
    })
    // Redirect the visiter to the website url
    window.location.href = link.data('url');
})
</script>
```

**Comment by krsmrs** [comment]
Hey there. That's great. What I'm going to need is a way to append the utm parameters captured in purser to certain links throughout a website. So I have a link for signups like  "http://mysignupwebsite.com/register" throughout my site ... and will want want the utm params string attached to it.

**Comment by bilbof** [comment]
Purser automatically creates a `visit` object whenever a user visits a page. I believe that UTM strings are stored in visit objects (let me know if they're not!). So when a user visits other pages on your site you could look at the `visit` objects for that page to see where they'd come from.

E.g. 

```
// convert the user
var attributes = purser.convert({})
// get all visits to the registration page
var registrationVisits = attributes.visits.filter((visit) => visit.landing_page == 'http://mywebsite.com/register')
// Get the UTM source code for the first visit
console.log(registrationVisits[0].utm_source)
```
